import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "./components/footer";
import Topone from "./components/Topone";
import TopTwoVersace from "./components/Toptwoversace";
import CustomHeader from "./components/Navbar";
import TopThreeBrowse from "./components/Topthreebrowse";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Shanze Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
      >
         <CustomHeader/>
        {children}     
        <Topone />
        <TopTwoVersace />
        <TopThreeBrowse />
        <Footer />
      </body>
    </html>
  );
}
